# Generated by Django 4.0.6 on 2022-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='tabdeal_price',
            new_name='asks_price',
        ),
        migrations.AddField(
            model_name='market',
            name='bids_price',
            field=models.DecimalField(decimal_places=16, max_digits=16, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='exchange',
            field=models.SmallIntegerField(choices=[(1, 'Tabdeal')], default=None),
            preserve_default=False,
        ),
    ]
