# Generated by Django 4.0.6 on 2022-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_collector', '0002_rename_tabdeal_price_market_asks_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
